language: node_js

node_js:
  - "0.10"
  - "0.11"

cache:
  directories:
    - node_modules

install:
  - npm install -g coveralls
  - npm install

script: npm run coverage

after_script:
  - cat ./coverage/lcov.info | coveralls
